-- ==========================================
-- 1. TABLES
-- ==========================================

-- Profiles: Master record for players
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  display_name TEXT,
  avatar_url TEXT,
  bio TEXT,
  total_games_played INT DEFAULT 0,
  total_wins INT DEFAULT 0,
  theme_preference TEXT DEFAULT 'system' CHECK (theme_preference IN ('light', 'dark', 'system')),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Sessions: The Mahjong Table
CREATE TABLE IF NOT EXISTS public.sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  current_dealer_idx INT DEFAULT 0,
  dealer_streak INT DEFAULT 0,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'closed'))
);

-- Session Players: Who is sitting where
CREATE TABLE IF NOT EXISTS public.session_players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id UUID REFERENCES public.sessions(id) ON DELETE CASCADE,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  seat_index INT CHECK (seat_index BETWEEN 0 AND 3),
  UNIQUE(session_id, seat_index),
  UNIQUE(session_id, profile_id)
);

-- Transactions: The Ledger (The "Why" of the scores)
CREATE TABLE IF NOT EXISTS public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  session_id UUID REFERENCES public.sessions(id) ON DELETE CASCADE,
  winner_index INT,
  loser_target TEXT, -- '0', '1', '2', '3', or 'all'
  base_points INT,
  dealer_at_time INT
);

-- ==========================================
-- 2. VIEWS (Live Score Calculation)
-- ==========================================

CREATE OR REPLACE VIEW public.session_scores AS
WITH RECURSIVE player_indices AS (
  SELECT generate_series(0, 3) AS p_idx
),
calc AS (
  SELECT 
    t.session_id,
    p.p_idx as player_idx,
    SUM(
      CASE 
        WHEN t.winner_index = p.p_idx THEN 
          CASE WHEN t.loser_target = 'all' THEN t.base_points * 3 ELSE t.base_points END
        WHEN t.loser_target = 'all' AND t.winner_index != p.p_idx THEN -t.base_points
        WHEN t.loser_target = p.p_idx::text THEN -t.base_points
        ELSE 0 
      END
    ) as total_score
  FROM public.transactions t
  CROSS JOIN player_indices p
  GROUP BY t.session_id, p.p_idx
)
SELECT * FROM calc;

-- ==========================================
-- 3. FUNCTIONS (The "Brain")
-- ==========================================

-- Function to record a win and rotate dealer
CREATE OR REPLACE FUNCTION record_mahjong_win(
  p_session_id UUID,
  p_winner_idx INT,
  p_loser_target TEXT,
  p_points INT,
  p_dealer_idx INT
) RETURNS void AS $$
DECLARE
    v_winner_profile_id UUID;
BEGIN
  -- Get winner profile to update stats
  SELECT profile_id INTO v_winner_profile_id 
  FROM public.session_players 
  WHERE session_id = p_session_id AND seat_index = p_winner_idx;

  -- 1. Insert Ledger Entry
  INSERT INTO public.transactions (session_id, winner_index, loser_target, base_points, dealer_at_time)
  VALUES (p_session_id, p_winner_idx, p_loser_target, p_points, p_dealer_idx);

  -- 2. Increment Winner Stats
  IF v_winner_profile_id IS NOT NULL THEN
    UPDATE public.profiles SET total_wins = total_wins + 1 WHERE id = v_winner_profile_id;
  END IF;

  -- 3. Dealer Rotation Logic
  IF p_winner_idx = p_dealer_idx THEN
    UPDATE public.sessions SET dealer_streak = dealer_streak + 1 WHERE id = p_session_id;
  ELSE
    UPDATE public.sessions SET current_dealer_idx = (p_dealer_idx + 1) % 4, dealer_streak = 0 WHERE id = p_session_id;
  END IF;
END;
$$ LANGUAGE plpgsql;

-- Function to archive table
CREATE OR REPLACE FUNCTION close_mahjong_session(p_session_id UUID)
RETURNS void AS $$
BEGIN
  UPDATE public.sessions SET status = 'closed' WHERE id = p_session_id;
  
  UPDATE public.profiles
  SET total_games_played = total_games_played + 1
  WHERE id IN (SELECT profile_id FROM public.session_players WHERE session_id = p_session_id);
END;
$$ LANGUAGE plpgsql;