-- ==========================================
-- 1. TABLES
-- ==========================================

-- Profiles: Master record for players
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  display_name TEXT,
  avatar_url TEXT,
  bio TEXT,
  is_admin BOOLEAN DEFAULT FALSE, -- Integrated Admin Flag
  total_games_played INT DEFAULT 0,
  total_wins INT DEFAULT 0,
  theme_preference TEXT DEFAULT 'system' CHECK (theme_preference IN ('light', 'dark', 'system')),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Sessions: The Mahjong Table
CREATE TABLE IF NOT EXISTS public.sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  current_dealer_idx INT DEFAULT 0,
  dealer_streak INT DEFAULT 0,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'closed'))
);

-- Session Players: Who is sitting where
CREATE TABLE IF NOT EXISTS public.session_players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id UUID REFERENCES public.sessions(id) ON DELETE CASCADE,
  -- profile_id is now NULLABLE to allow for Guest Mode
  profile_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NULL, 
  guest_name TEXT, -- Integrated Guest Name
  seat_index INT CHECK (seat_index BETWEEN 0 AND 3),
  
  -- Ensure a seat is unique per session
  UNIQUE(session_id, seat_index),
  -- Ensure a registered user can only occupy one seat per session
  -- (Guests are excluded from this specific constraint as profile_id is NULL)
  UNIQUE(session_id, profile_id)
);

-- Transactions: The Ledger
CREATE TABLE IF NOT EXISTS public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  session_id UUID REFERENCES public.sessions(id) ON DELETE CASCADE,
  winner_index INT,
  loser_target TEXT, 
  base_points INT,
  dealer_at_time INT
);

-- ==========================================
-- 2. VIEWS & FUNCTIONS
-- ==========================================
-- [Keep your existing View and Functions here...]

-- New Function: Undo Logic (Added to the core schema)
CREATE OR REPLACE FUNCTION undo_last_transaction(p_session_id UUID)
RETURNS void AS $$
DECLARE
    v_last_tx_id BIGINT;
    v_prev_dealer_idx INT;
BEGIN
    SELECT id, dealer_at_time INTO v_last_tx_id, v_prev_dealer_idx
    FROM public.transactions
    WHERE session_id = p_session_id
    ORDER BY created_at DESC
    LIMIT 1;

    IF v_last_tx_id IS NOT NULL THEN
        DELETE FROM public.transactions WHERE id = v_last_tx_id;
        UPDATE public.sessions 
        SET current_dealer_idx = v_prev_dealer_idx,
            dealer_streak = GREATEST(0, dealer_streak - 1)
        WHERE id = p_session_id;
    END IF;
END;
$$ LANGUAGE plpgsql;